// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Decks, _;

  _ = require('lodash');

  Decks = (function() {
    function Decks(base, options1) {
      this.base = base;
      this.options = options1;
      this._decks = {};
    }

    Decks.prototype.define = function(name, options) {
      var deck;
      if (options == null) {
        options = {};
      }
      options = _.defaultsDeep(options, this.options);
      options.name = name;
      options.base = this.base;
      this._decks[name] = deck = new this.options.deck_type(options);
      this.base.trigger('deck:new', deck, options);
      return deck;
    };

    Decks.prototype.get = function(name) {
      var deck;
      deck = this._decks[name];
      if (!deck) {
        throw new Error("No such deck " + name + "!");
      }
      return deck;
    };

    return Decks;

  })();

  module.exports = Decks;

}).call(this);
