// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Modules;

  Modules = (function() {
    function Modules(options) {
      this.options = options;
      this._mod_types = {};
    }

    Modules.prototype.define = function(module_type, constructor) {
      return this._mod_types[module_type] = constructor;
    };

    Modules.prototype.get = function(module_type) {
      var mod_type;
      mod_type = this._mod_types[module_type];
      if (!mod_type) {
        throw new Error("No such module type " + module_type + "!");
      }
      return mod_type;
    };

    return Modules;

  })();

  module.exports = Modules;

}).call(this);
