// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(test, errorMessage) {
    if (!test) {
      throw new Error(errorMessage);
    }
  };

}).call(this);

//# sourceMappingURL=assert.js.map
