// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var CardStackView, Dreamhorn;

  Dreamhorn = require('dreamhorn');

  CardStackView = (function() {
    function CardStackView(deck, options) {
      this.deck = deck;
      this.options = options;
    }

    return CardStackView;

  })();

  module.exports = CardStackView;

}).call(this);
