// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var CardStackViewModule, Dreamhorn, assert;

  assert = require('assert-error');

  Dreamhorn = require('dreamhorn');

  CardStackViewModule = (function() {
    function CardStackViewModule(deck, options) {
      this.deck = deck;
      this.options = options;
      this.options = this.options || {};
      assert(this.options['container'], "CardStackView requires a `container` option");
      this.container = this.options['container'];
    }

    return CardStackViewModule;

  })();

  module.exports = CardStackViewModule;

}).call(this);
