// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Card, When, _, md5;

  _ = require('lodash');

  md5 = require('md5');

  When = require('when');

  Card = (function() {
    function Card(id, data) {
      if (_.isUndefined(data)) {
        data = id;
        id = void 0;
      }
      if (_.isString(data)) {
        data = {
          content: data,
          id: id
        };
      }
      if (!data.id) {
        if (!id) {
          data.id = md5(JSON.stringify(data));
        } else {
          data.id = id;
        }
      }
      data.id = data.id.toLowerCase();
      _.assign(this, data);
      this.index = null;
    }

    Card.prototype.will_get_attribute = When.lift(function(name, options, deck, _default) {
      var value;
      if (_default == null) {
        _default = '';
      }
      value = this[name];
      if (_.isFunction(value)) {
        value = value(options, deck);
      }
      return When(value).then(function(value) {
        return value || _default;
      });
    });

    Card.prototype.will_get_header = function(options, deck) {
      return this.will_get_attribute('header', options, deck);
    };

    Card.prototype.will_get_content = function(options, deck) {
      return this.will_get_attribute('content', options, deck);
    };

    Card.prototype.will_get_choices = function(options, deck) {
      var _default, choices;
      return choices = this.will_get_attribute('choices', options, deck, _default = {});
    };

    return Card;

  })();

  module.exports = Card;

}).call(this);

//# sourceMappingURL=card.js.map
