// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Dispatcher, smokesignals;

  smokesignals = require('smokesignals');

  Dispatcher = (function() {
    function Dispatcher() {
      smokesignals.convert(this);
    }

    return Dispatcher;

  })();

  module.exports = Dispatcher;

}).call(this);
