// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Dict, Dreamhorn, Handlebars, ViewModule, When, _, _template_cache, dom;

  _ = require('lodash');

  dom = require('./dom');

  Dict = require('collections/dict');

  When = require('when');

  Handlebars = require('handlebars');

  Dreamhorn = require('./dreamhorn');

  _template_cache = new Dict();

  ViewModule = (function() {
    ViewModule.prototype.events = {};

    ViewModule.prototype.defaults = {
      template: '',
      effect_in: 'default-in',
      effect_out: 'default-out'
    };

    function ViewModule(deck, options) {
      this.deck = deck;
      this.options = _.defaultsDeep({}, options, this.defaults, this.constructor.__super__.defaults);
      this.template = this.options.template ? Handlebars.compile(this.options.template) : function() {
        return '';
      };
      _.bindAll(this);
      this.selector = this.options.selector;
      this.el = this.options.el;
      this.subviews = {};
    }

    ViewModule.prototype.get_context = function() {
      return {};
    };

    ViewModule.prototype.render = function(context) {
      return this.render_template(this.template, context);
    };

    ViewModule.prototype.render_template = function(template, context) {
      var ambient, ctx;
      context = context || {};
      ambient = {};
      this.deck.trigger('context:get', ambient);
      ctx = _.defaultsDeep({}, context, this.get_context(), this.options, ambient);
      return this.get_compiled_template(template)(ctx);
    };

    ViewModule.prototype.get_compiled_template = function(template) {
      var render;
      if (_.isFunction(template)) {
        render = template;
      } else {
        if (_template_cache.has(template)) {
          render = _template_cache.get(template);
        } else {
          render = Handlebars.compile(template);
          _template_cache.set(template, render);
        }
      }
      return render;
    };

    ViewModule.prototype.connect_events = function() {
      var event, event_selector, handler, handler_name, ref, ref1, selector;
      ref = this.events;
      for (event_selector in ref) {
        handler_name = ref[event_selector];
        ref1 = event_selector.split(/\s+/, 2), event = ref1[0], selector = ref1[1];
        handler = this[handler_name];
        if (_.isFunction(handler)) {
          dom.on(this.el, event, selector, handler);
        }
      }
    };

    ViewModule.prototype.disconnect_events = function() {
      var event, event_selector, handler, handler_name, ref, ref1, selector;
      ref = this.events;
      for (event_selector in ref) {
        handler_name = ref[event_selector];
        ref1 = event_selector.split(/\s+/, 2), event = ref1[0], selector = ref1[1];
        handler = this[handler_name];
        if (_.isFunction(handler)) {
          dom.off(this.el, event, handler);
        }
      }
    };

    ViewModule.prototype.setup = function() {};

    ViewModule.prototype.animate_in = function() {
      return this.deck.base.effects.run(this.options.effect_in, this.el, this.options, this);
    };

    ViewModule.prototype.teardown = function() {};

    ViewModule.prototype.animate_out = function() {
      return this.deck.base.effects.run(this.options.effect_out, this.el, this.options, this);
    };

    ViewModule.prototype.start = function() {
      if (this.selector && !this.el) {
        this.el = dom.query(this.selector)[0];
      } else if (!this.selector && !this.el) {
        this.el = dom.make(this.render());
      }
      return When["try"](this.setup).then(this.animate_in).then(this.connect_events);
    };

    ViewModule.prototype.stop = function() {
      return When["try"](this.disconnect_events).then(this.animate_out).then(this.teardown).then((function(_this) {
        return function() {
          return _this.el = null;
        };
      })(this));
    };

    ViewModule.prototype.use_subview = function(arg) {
      var mod, options, subview_id, subview_type;
      subview_id = arg.id, subview_type = arg.type, options = arg.options;
      mod = this.subviews[subview_id] = {
        id: subview_id,
        instance: new subview_type(this.deck, options),
        type: subview_type,
        deck: this.deck,
        options: options,
        active: false
      };
      return this.deck.trigger('subview:used', mod).then((function(_this) {
        return function() {
          return mod.instance;
        };
      })(this));
    };

    ViewModule.prototype.get_subview = function(subview_id) {
      var mod;
      mod = this.subviews[subview_id];
      if (!mod) {
        throw new Error("No such subview instance with id " + subview_id + "!");
      }
      return mod;
    };

    ViewModule.prototype.start_subview = function(subview_id) {
      var mod;
      mod = this.get_subview(subview_id);
      if (!mod.active) {
        this.deck.trigger('subview:starting', mod);
        if (_.isFunction(mod.instance.start)) {
          mod.instance.start();
        }
        mod.active = true;
        return this.deck.trigger('subview:started', mod).then(function() {
          return mod.instance;
        });
      } else {
        return When(mod.instance);
      }
    };

    ViewModule.prototype.stop_subview = function(subview_id) {
      var mod;
      mod = this.get_subview(subview_id);
      if (mod.active) {
        this.deck.trigger('subview:stopping', mod);
        if (_.isFunction(mod.instance.stop)) {
          mod.instance.stop();
        }
        mod.active = false;
        return this.deck.trigger('subview:stopped', mod).then(function() {
          return mod.instance;
        });
      } else {
        return When(mod.instance);
      }
    };

    return ViewModule;

  })();

  module.exports = ViewModule;

}).call(this);

//# sourceMappingURL=mod-view.js.map
