// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Dict, Dreamhorn, Handlebars, ViewModule, When, _, _template_cache, dom, marked;

  _ = require('lodash');

  marked = require('marked');

  dom = require('./dom');

  Dict = require('collections/dict');

  When = require('when');

  Handlebars = require('handlebars');

  Dreamhorn = require('./dreamhorn');

  _template_cache = new Dict();

  ViewModule = (function() {
    ViewModule.prototype.events = {};

    ViewModule.prototype.defaults = {
      template: '',
      effect_in: 'default-in',
      effect_out: 'default-out'
    };

    function ViewModule(deck, options) {
      this.deck = deck;
      this.options = _.defaultsDeep({}, options, this.defaults, this.constructor.__super__.defaults);
      this.template = this.options.template ? Handlebars.compile(this.options.template) : function() {
        return '';
      };
      _.bindAll(this);
      this.selector = this.options.selector;
      this.el = this.options.el;
      this.subviews = {};
    }

    ViewModule.prototype.get_context = function() {
      return {};
    };

    ViewModule.prototype.will_get_ambient_context = function() {
      var ambient;
      ambient = {};
      return this.deck.trigger('context:get', ambient).then(function() {
        return ambient;
      });
    };

    ViewModule.prototype.will_get_context = function(overrides) {
      var ambient_context, local_context;
      ambient_context = this.will_get_ambient_context();
      local_context = When(this.get_context());
      return When.join(local_context, ambient_context).then((function(_this) {
        return function(arg) {
          var ambient, local;
          ambient = arg[0], local = arg[1];
          return _.defaultsDeep({}, overrides, local, ambient, _this.options);
        };
      })(this));
    };

    ViewModule.prototype.will_render = function(overrides) {
      var context_p;
      context_p = this.will_get_context(overrides);
      return this.will_render_template(this.template, context_p);
    };

    ViewModule.prototype.will_render_template = function(template, context) {
      var compiled_p, context_p;
      compiled_p = this.will_get_compiled_template(template);
      context_p = When(context);
      return When.join(compiled_p, context_p).then(function(arg) {
        var compiled, context;
        compiled = arg[0], context = arg[1];
        return compiled(context);
      });
    };

    ViewModule.prototype.convert_to_markdown = function(text) {
      return marked(text);
    };

    ViewModule.prototype.will_get_compiled_template = function(template) {
      var promised;
      if (_.isFunction(template)) {
        promised = When(template);
      } else {
        if (_template_cache.has(template)) {
          promised = When(_template_cache.get(template));
        } else {
          promised = this.will_convert_to_template(template).then(function(render) {
            _template_cache.set(template, render);
            return render;
          });
        }
      }
      return promised;
    };

    ViewModule.prototype.will_convert_to_template = function(content) {
      var _imports;
      if (_.isFunction(content)) {
        content = content(this.options, this.deck);
      }
      _imports = {
        pronoun: pronoun,
        _: _
      };
      return this.deck.trigger('set-template-imports', _imports).then((function(_this) {
        return function() {
          var template;
          template = Handlebars.compile(content);
          return function(context) {
            var _tmpl, result;
            result = template(context);
            _tmpl = _.template(result, {
              imports: _imports
            });
            return _tmpl(context);
          };
        };
      })(this));
    };

    ViewModule.prototype.connect_events = function() {
      var event, event_selector, handler, handler_name, ref, ref1, selector;
      ref = this.events;
      for (event_selector in ref) {
        handler_name = ref[event_selector];
        ref1 = event_selector.split(/\s+/, 2), event = ref1[0], selector = ref1[1];
        handler = this[handler_name];
        if (_.isFunction(handler)) {
          dom.on(this.el, event, selector, handler);
        }
      }
    };

    ViewModule.prototype.disconnect_events = function() {
      var event, event_selector, handler, handler_name, ref, ref1, selector;
      ref = this.events;
      for (event_selector in ref) {
        handler_name = ref[event_selector];
        ref1 = event_selector.split(/\s+/, 2), event = ref1[0], selector = ref1[1];
        handler = this[handler_name];
        if (_.isFunction(handler)) {
          dom.off(this.el, event, handler);
        }
      }
    };

    ViewModule.prototype.setup = function() {};

    ViewModule.prototype.will_animate_in = function() {
      return this.deck.base.effects.run(this.options.effect_in, this.el, this.options, this);
    };

    ViewModule.prototype.teardown = function() {};

    ViewModule.prototype.will_animate_out = function() {
      return this.deck.base.effects.run(this.options.effect_out, this.el, this.options, this);
    };

    ViewModule.prototype.start = function() {
      if (this.selector && !this.el) {
        this.el = dom.query(this.selector)[0];
      } else if (!this.selector && !this.el) {
        this.el = this.will_render().then((function(_this) {
          return function(html) {
            return _this.el = dom.make(html);
          };
        })(this));
      }
      return When.join(this.el, this.setup()).then(this.will_animate_in).then(this.connect_events);
    };

    ViewModule.prototype.stop = function() {
      return When["try"](this.disconnect_events).then(this.will_animate_out).then(this.teardown).then((function(_this) {
        return function() {
          return _this.el = null;
        };
      })(this));
    };

    ViewModule.prototype.will_use_subview = function(arg) {
      var mod, options, subview_id, subview_type;
      subview_id = arg.id, subview_type = arg.type, options = arg.options;
      mod = this.subviews[subview_id] = {
        id: subview_id,
        instance: new subview_type(this.deck, options),
        type: subview_type,
        deck: this.deck,
        options: options,
        active: false
      };
      return this.deck.trigger('subview:used', mod).then((function(_this) {
        return function() {
          return mod.instance;
        };
      })(this));
    };

    ViewModule.prototype.get_subview = function(subview_id) {
      var mod;
      mod = this.subviews[subview_id];
      if (!mod) {
        throw new Error("No such subview instance with id " + subview_id + "!");
      }
      return mod;
    };

    ViewModule.prototype.will_start_subview = function(subview_id) {
      var mod, promises;
      promises = [];
      mod = this.get_subview(subview_id);
      if (!mod.active) {
        promises.push(this.deck.trigger('subview:starting', mod));
        if (_.isFunction(mod.instance.start)) {
          promises.push(mod.instance.start());
        }
        mod.active = true;
        promises.push(this.deck.trigger('subview:started', mod).then(function() {
          return mod.instance;
        }));
      } else {
        promises.push(When(mod.instance));
      }
      return When.all(promises).then(function() {
        return mod.instance;
      });
    };

    ViewModule.prototype.will_stop_subview = function(subview_id) {
      var mod, promises;
      promises = [];
      mod = this.get_subview(subview_id);
      if (mod.active) {
        promises.push(this.deck.trigger('subview:stopping', mod));
        if (_.isFunction(mod.instancpe.stop)) {
          promises.push(mod.instance.stop());
        }
        mod.active = false;
        promises.push(this.deck.trigger('subview:stopped', mod).then(function() {
          return mod.instance;
        }));
      } else {
        promises.push(When(mod.instance));
      }
      return When.all(promises);
    };

    return ViewModule;

  })();

  module.exports = ViewModule;

}).call(this);

//# sourceMappingURL=mod-view.js.map
