// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Situation, _, md5;

  _ = require('lodash');

  md5 = require('md5');

  Situation = (function() {
    function Situation(id, data) {
      if (_.isUndefined(data)) {
        data = id;
        id = void 0;
      }
      if (_.isString(data)) {
        data = {
          content: data,
          id: id
        };
      }
      if (!data.id) {
        if (!id) {
          data.id = md5(JSON.stringify(data));
        } else {
          data.id = id;
        }
      }
      data.id = data.id.toLowerCase();
      _.assign(this, data);
      this.index = null;
    }

    return Situation;

  })();

  module.exports = Situation;

}).call(this);
