// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Events, Stack, _,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _ = require('lodash');

  Events = require('./events');

  Stack = (function(superClass) {
    extend(Stack, superClass);

    function Stack() {
      this.clear();
    }

    Stack.prototype.clear = function(data) {
      this._data = [null];
      this.length = 0;
      return this.trigger('cleared', data);
    };

    Stack.prototype.push = function(item, data) {
      this.length += 1;
      this._data[this.length] = item;
      this.trigger('pushed', item, data);
      return this;
    };

    Stack.prototype.peek = function() {
      return this._data[this.length];
    };

    Stack.prototype.pop = function(data) {
      var popped;
      if (this.length > 0) {
        this.length -= 1;
        popped = this._data.pop();
        this.trigger('popped', popped, data);
        return popped;
      } else {
        return void 0;
      }
    };

    Stack.prototype.drop = function(item, data) {
      var dropped;
      dropped = _.remove(this._data, _.matchesProperty('id', item.id))[0];
      this.length = this._data.length - 1;
      this.trigger('dropped', dropped, data);
      return dropped;
    };

    return Stack;

  })(Events);

  module.exports = Stack;

}).call(this);

//# sourceMappingURL=stack.js.map
