// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Dict, Handlebars, _, marked;

  Handlebars = require('handlebars');

  _ = require('./util');

  marked = require('marked');

  Dict = require('collections/dict');

  module.exports = {
    _template_cache: new Dict(),
    compile_template: function(content, _imports) {
      var template;
      _imports = _imports || {
        _: _
      };
      template = Handlebars.compile(content);
      return function(context) {
        var _tmpl, result;
        result = template(context);
        _tmpl = _.template(result, {
          imports: _imports
        });
        return _tmpl(context);
      };
    },
    get_compiled_template: function(template) {
      var render;
      if (_.isFunction(template)) {
        render = template;
      } else {
        if (this._template_cache.has(template)) {
          render = When(_template_cache.get(template));
        } else {
          render = this.compile_template(template);
        }
      }
      return render;
    },
    render_template: function(template, context) {
      var render;
      render = this.get_compiled_template(template);
      return render(context);
    },
    convert_markdown_to_html: function(text) {
      return marked(text);
    }
  };

}).call(this);

//# sourceMappingURL=templates.js.map
